# Generated by Django 5.0.3 on 2024-04-01 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 18, 54, 22, 227893), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 18, 54, 22, 227893), verbose_name='end date'),
        ),
    ]
