# Generated by Django 5.0.3 on 2024-05-13 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_task_creation_date_alter_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 13, 53, 13, 697015), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 13, 53, 13, 697015), verbose_name='end date'),
        ),
    ]
